#############################################################################
# File name:  Makefile
# Author:     chadd williams
# Date:       Jan 26, 2024
# Class:      CS445
# Assignment: SoftwareDB
# Purpose:    build PDF files
#############################################################################


all: 

ENSCRIPT_FLAGS=-C -T 2 -p - -M Letter -Esql --color -fCourier8


